/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ResidentRole;

import Business.Enterprise.Committee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ResidentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Rate;
import Business.WorkQueue.ServiceResult;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author josef
 */
public class RateJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
UserAccount account;
ResidentOrganization organization;
Enterprise enterprise;
Network network;
int grade;
String s=new String();
ArrayList<Rate> rateList;
    /**
     * Creates new form RateJPanel
     */

    RateJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, ArrayList<Rate> rateList) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.account=account;
       this.organization=organization;
       this.enterprise=enterprise;
       this.network=network;
       this.rateList = rateList;
       grade=0;
       populateCombobox();
    }
    
     public void populateCombobox(){
        CBX.removeAllItems();
        for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise.getEnterpriseType().getValue().equals("ServiceDepartment")){
                 CBX.addItem(enterprise);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b4 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        b1 = new javax.swing.JRadioButton();
        b7 = new javax.swing.JRadioButton();
        b5 = new javax.swing.JRadioButton();
        b8 = new javax.swing.JRadioButton();
        b9 = new javax.swing.JRadioButton();
        b6 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        btnFinish = new javax.swing.JButton();
        txtRate = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbx = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        CBX = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("微软雅黑", 2, 24)); // NOI18N
        jLabel1.setText("Grade My Experience");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel2.setText("Be On Time or Not");

        b4.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        b4.setForeground(new java.awt.Color(51, 51, 255));
        b4.setText("Good");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        b2.setForeground(new java.awt.Color(51, 102, 255));
        b2.setText("Fair");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        b3.setForeground(new java.awt.Color(51, 102, 255));
        b3.setText("Bad");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel3.setText("Finished as Expected");

        b1.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        b1.setForeground(new java.awt.Color(51, 51, 255));
        b1.setText("Good");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        b7.setForeground(new java.awt.Color(51, 51, 255));
        b7.setText("Good");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        b5.setForeground(new java.awt.Color(51, 102, 255));
        b5.setText("Fair");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        b8.setForeground(new java.awt.Color(51, 102, 255));
        b8.setText("Fair");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        b9.setForeground(new java.awt.Color(51, 102, 255));
        b9.setText("Bad");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        b6.setForeground(new java.awt.Color(51, 102, 255));
        b6.setText("Bad");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jLabel4.setText("Service Quality");

        btnFinish.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N

        cbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));

        CBX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b9)
                                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(b2)
                            .addComponent(b3)
                            .addComponent(b1))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(b4)
                            .addComponent(b5)
                            .addComponent(b6))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b8)
                            .addComponent(b7)
                            .addComponent(b9)
                            .addComponent(jLabel4))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFinish)
                            .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(7, 7, 7)
                        .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ResidentReportJPanel rrj = (ResidentReportJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
        String value=null;
        grade=0;
        //s=null;
        if(b1.isSelected()){
            grade=grade+3;
        }
        if(b2.isSelected()){
            grade=grade+2;
        }
        if(b3.isSelected()){
            grade=grade+1;
        }
        if(b4.isSelected()){
            grade=grade+3;
        }
        if(b5.isSelected()){
            grade=grade+2;
        }
        if(b6.isSelected()){
            grade=grade+1;
        }
        if(b7.isSelected()){
            grade=grade+3;
        }
        if(b8.isSelected()){
            grade=grade+2;
        }
        if(b9.isSelected()){
            grade=grade+1;
        }
        if(grade>=1 && grade<6){
            value="C";
        }
        if(grade>=6 && grade <7){
            value="B";
        }
        if(grade>=7 && grade<=10){
            value="A";
        }
        txtRate.setText(value);
        jLabel9.setText(value);
        jLabel7.setText("Thank you! Your feedback will be sent soon!");
        String message1=value;
        Enterprise enterprise1= (Enterprise)CBX.getSelectedItem();
        Rate rate = new Rate();
        rate.setRate(message1);
        rate.setResident(account);
        enterprise1.getRateList().getRateList().add(rate);

        JOptionPane.showMessageDialog(null,"Your feedback has been sent successfully!");
        /*
        Enterprise enterprise1 = (Enterprise)cbx.getSelectedItem();
        String message=txtIssue.getText();
        //SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
        Date requestDate=jDateChooser.getDate();
        ReportingResult request=new ReportingResult();
        request.setRequestDate(requestDate);
        request.setMessage(message);
        request.setSender(account);
        request.setStatus("Sent by "+account.getUsername());

        account.getRequestQueue().getRequestList().add(request);
        enterprise1.getRequestQueue().getRequestList().add(request);
        */

    }//GEN-LAST:event_btnFinishActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if(b1.isSelected()){
            b2.setSelected(false);
            b3.setSelected(false);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
         if(b2.isSelected()){
            b1.setSelected(false);
            b3.setSelected(false);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
           if(b3.isSelected()){
            b1.setSelected(false);
            b2.setSelected(false);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
           if(b4.isSelected()){
            b5.setSelected(false);
            b6.setSelected(false);
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
           if(b5.isSelected()){
            b4.setSelected(false);
            b6.setSelected(false);
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
           if(b6.isSelected()){
            b5.setSelected(false);
            b4.setSelected(false);
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
           if(b7.isSelected()){
            b8.setSelected(false);
            b9.setSelected(false);
        }
        
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
           if(b8.isSelected()){
            b7.setSelected(false);
            b9.setSelected(false);
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
           if(b9.isSelected()){
            b8.setSelected(false);
            b7.setSelected(false);
        }
    }//GEN-LAST:event_b9ActionPerformed
        

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBX;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.JRadioButton b4;
    private javax.swing.JRadioButton b5;
    private javax.swing.JRadioButton b6;
    private javax.swing.JRadioButton b7;
    private javax.swing.JRadioButton b8;
    private javax.swing.JRadioButton b9;
    private javax.swing.JButton btnFinish;
    private javax.swing.JComboBox cbx;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtRate;
    // End of variables declaration//GEN-END:variables
}
