/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ResidentRole;

import Business.Product.Provider;
import Business.Product.Product;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.ReportingOrganization;
import Business.Organization.ResidentOrganization;
import Business.UserAccount.UserAccount;
import Interface.ProvideRole.UpdateProductJPanel;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author josef
 */
public class ResidentWorkArea extends javax.swing.JPanel {
JPanel userProcessContainer;
UserAccount account;
ResidentOrganization organization;
Enterprise enterprise;
Network network;
String path;

    /**
     * Creates new form ResidentWorkArea
     */
 
    public ResidentWorkArea(JPanel userProcessContainer, UserAccount account, ResidentOrganization organization, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.organization=organization;
        this.enterprise=enterprise;
        this.network=network;
        jLabel4.setText(account.getUsername());
        
        
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        residentLable = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnAttach = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        txtIMG = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        residentLable.setFont(new java.awt.Font("微软雅黑", 3, 36)); // NOI18N

        setForeground(new java.awt.Color(51, 204, 255));

        jLabel2.setFont(new java.awt.Font("微软雅黑", 3, 36)); // NOI18N
        jLabel2.setText("Welcome !");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel3.setText("I want to:");

        btnOrder.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnOrder.setText("Order Product");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnReport.setText("Report Status");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnAttach.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnAttach.setText("Upload");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("微软雅黑", 2, 18)); // NOI18N
        jLabel1.setText("Upload your photo here");

        jLabel4.setFont(new java.awt.Font("宋体", 3, 24)); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAttach)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnOrder))
                        .addGap(43, 43, 43)
                        .addComponent(btnReport))
                    .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAttach))
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(0, 198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
            ResidentOrderJPanel roj=new ResidentOrderJPanel(userProcessContainer,organization,enterprise,network);
            userProcessContainer.add("roj",roj);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
            ResidentReportJPanel rrj=new ResidentReportJPanel(userProcessContainer,account, organization,enterprise,network);
            userProcessContainer.add("rrj",rrj);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnReportActionPerformed
    
   /* public void populateimage(String url, JLabel lbl) {

            ImageIcon imageIcon = new ImageIcon("C:\\Users\\josef\\Desktop\\5100\\FinalBank\\images.jpg");
            Image image = imageIcon.getImage();
            Image smallImage = image.getScaledInstance(200, 200, Image.SCALE_FAST);
            ImageIcon smallIcon = new ImageIcon(smallImage);
            lbl.setIcon(smallIcon);
            
    }*/

    
    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        // TODO add your handling code here:
       path=null;
       JFileChooser jfc=new JFileChooser();
       jfc.showOpenDialog(null);
       File pic=jfc.getSelectedFile();
       if(pic!=null&&pic.getAbsolutePath().endsWith(".jpg")){
           path=pic.getAbsolutePath();
           ImageIcon imageIcon=new ImageIcon(path);
           Image image=imageIcon.getImage();
           Image smallImage=image.getScaledInstance(250, 250, Image.SCALE_FAST);
           ImageIcon smallIcon=new ImageIcon(smallImage);
           lbl.setIcon(smallIcon);
       }
      /* JFileChooser choose=new JFileChooser();
        choose.showOpenDialog(null);
        File f=choose.getSelectedFile();
        
        String filename=f.getAbsolutePath();
        
                    
        txtIMG.setText(filename);
        ImageIcon imageIcon=new ImageIcon(filename);
        lbl.setIcon(imageIcon);
        txtIMG.setText("");*/
    }//GEN-LAST:event_btnAttachActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel residentLable;
    private javax.swing.JTextField txtIMG;
    // End of variables declaration//GEN-END:variables
}
