/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ResidentRole;

import Business.Enterprise.Committee;
import Business.Enterprise.Enterprise;
import static Business.Enterprise.Enterprise.EnterpriseType.Committee;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.ReportingOrganization;
import Business.Organization.ResidentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ReportingResult;
import Business.WorkQueue.Request;
import Business.WorkQueue.RequestQueue;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import Business.Enterprise.ReportingDepartment;
import Business.WorkQueue.Rate;
import Business.WorkQueue.ServiceResult;
import java.util.ArrayList;

/**
 *
 * @author josef
 */
public class ResidentReportJPanel extends javax.swing.JPanel {
JPanel userProcessContainer;
UserAccount account;
Organization organization;
Committee enterprise;
Network network;
ArrayList<Rate> rateList = new ArrayList();
    /**
     * Creates new form ResidentReportJPanel
     */
  

    ResidentReportJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network) {
          initComponents();
          this.userProcessContainer=userProcessContainer;
          this.account=account;
          this.organization=organization;
          //this.enterprise=enterprise;
          this.enterprise=(Committee)enterprise;
          this.network=network;
          userLable.setText(account.getUsername());
          enterpriseLable.setText(enterprise.getName());
          populateRequestTable();
          populatefeedbackTable();
          //populateComboBox();
    }
     /*public void populateComboBox(){
        cbx.removeAllItems();
        for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
            if(enterprise.getEnterpriseType().getValue().equals("Committee")){
                 cbx.addItem(enterprise);
            }
        }
    }*/
    public void populateRequestTable(){
        DefaultTableModel model=(DefaultTableModel) requestTable.getModel();
        model.setRowCount(0);
        for(Request request:account.getRequestQueue().getRequestList()){
            Object row[]=new Object[4];
            row[0]=request;
            row[1]=request.getSender();
            row[2]=request.getStatus();
            /*String reportingStatus=((ReportingResult) request).getReportingStatus();
            row[3]= reportingStatus==null ? "Waiting Confirm":reportingStatus;*/
            SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
            if(request.getRequestDate() != null) 
            row[3]=dateFormat.format(request.getRequestDate()) ;
          
            //row[4]=  request.getSender().getEmployee().getName();
            
            model.addRow(row);
        }
    }
    
    public void populatefeedbackTable(){
        DefaultTableModel dtm=(DefaultTableModel)feedbackTable.getModel();
        dtm.setRowCount(0);
        for(Request request1:enterprise.getRequestQueue().getRequestList()){
            Object[] row=new Object[3];
            row[0]=request1;
            row[1]=request1.getSender().getEmployee().getName();
            //row[2]=request.getMessage();
            String result1=((ServiceResult)request1).getResolveResult();
            row[2]=result1;
            dtm.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enterpriseLable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userLable = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        feedbackTable = new javax.swing.JTable();
        btnRate = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("Report Your Issues Here");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        jLabel2.setText("Department:");

        enterpriseLable.setFont(new java.awt.Font("微软雅黑", 1, 24)); // NOI18N
        enterpriseLable.setText("<value>");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 0));
        jLabel3.setText("Welcome!");

        userLable.setFont(new java.awt.Font("微软雅黑", 3, 24)); // NOI18N
        userLable.setForeground(new java.awt.Color(102, 102, 0));
        userLable.setText("<value>");

        requestTable.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        requestTable.setForeground(new java.awt.Color(255, 0, 0));
        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Status", "Reporting Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestTable);
        if (requestTable.getColumnModel().getColumnCount() > 0) {
            requestTable.getColumnModel().getColumn(0).setResizable(false);
            requestTable.getColumnModel().getColumn(1).setResizable(false);
            requestTable.getColumnModel().getColumn(2).setResizable(false);
            requestTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("微软雅黑", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 0));
        jLabel4.setText("I want to:");

        btnReport.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnBack.setText("Go Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        feedbackTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        feedbackTable.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        feedbackTable.setForeground(new java.awt.Color(0, 51, 51));
        feedbackTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Original Issue", "Tackled By", "Result"
            }
        ));
        jScrollPane2.setViewportView(feedbackTable);

        btnRate.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        btnRate.setText("Rate");
        btnRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(64, 64, 64)
                                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jButton1)
                                .addGap(59, 59, 59)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnBack)
                        .addGap(44, 44, 44)
                        .addComponent(btnRate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(userLable)
                        .addGap(155, 155, 155)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(enterpriseLable, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel1)))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userLable)
                    .addComponent(jLabel2)
                    .addComponent(enterpriseLable))
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnReport)
                    .addComponent(jButton1)
                    .addComponent(btnRefresh))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(295, 295, 295))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnRate))
                .addGap(218, 218, 218))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateRequestTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("PlaceMessageJPanel",new LeaveMessageJPanel(userProcessContainer,account,enterprise,network));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow=requestTable.getSelectedRow();
        if(selectedRow>=0){
            Request request=(Request)requestTable.getValueAt(selectedRow, 0);
            account.getRequestQueue().deleteRequest(request);
            JOptionPane.showMessageDialog(null, "Request deleted successfully!");
            populateRequestTable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ResidentWorkArea rwa = (ResidentWorkArea) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRateActionPerformed
        // TODO add your handling code here:
        CardLayout layout=(CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RateJPanel",new RateJPanel(userProcessContainer,account,enterprise,network,rateList));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRate;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel enterpriseLable;
    private javax.swing.JTable feedbackTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable requestTable;
    private javax.swing.JLabel userLable;
    // End of variables declaration//GEN-END:variables
}
